# Generated by Django 3.2.10 on 2022-05-15 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('link', models.FloatField(max_length=300, null=True)),
                ('category', models.CharField(choices=[('Happy', 'Happy'), ('anger', 'ager'), ('fear', 'fear'), ('sadness', 'sadness'), ('contempt', 'contempt'), ('disgust', 'disgust'), ('surprise', 'surprise')], max_length=200, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
