# Generated by Django 3.2.10 on 2022-05-15 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRED', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videos',
            name='link',
        ),
        migrations.AddField(
            model_name='videos',
            name='url_link',
            field=models.URLField(null=True),
        ),
    ]
