# Generated by Django 3.2.10 on 2022-05-15 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRED', '0002_auto_20220515_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='image',
            field=models.ImageField(default='', upload_to='static/images'),
        ),
    ]
