# Generated by Django 3.2.10 on 2022-05-15 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRED', '0003_videos_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('url_link', models.URLField(null=True)),
                ('category', models.CharField(choices=[('Happy', 'Happy'), ('anger', 'ager'), ('fear', 'fear'), ('sadness', 'sadness'), ('contempt', 'contempt'), ('disgust', 'disgust'), ('surprise', 'surprise')], max_length=200, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('image', models.ImageField(default='', upload_to='static/images')),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('url_link', models.URLField(null=True)),
                ('category', models.CharField(choices=[('Happy', 'Happy'), ('anger', 'ager'), ('fear', 'fear'), ('sadness', 'sadness'), ('contempt', 'contempt'), ('disgust', 'disgust'), ('surprise', 'surprise')], max_length=200, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('image', models.ImageField(default='', upload_to='static/images')),
            ],
        ),
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('url_link', models.URLField(null=True)),
                ('category', models.CharField(choices=[('Happy', 'Happy'), ('anger', 'ager'), ('fear', 'fear'), ('sadness', 'sadness'), ('contempt', 'contempt'), ('disgust', 'disgust'), ('surprise', 'surprise')], max_length=200, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('image', models.ImageField(default='', upload_to='static/images')),
            ],
        ),
    ]
