# Generated by Django 3.2.10 on 2022-05-15 19:30

import CRED.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRED', '0005_rename_audio_audios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audios',
            name='image',
            field=models.ImageField(default='', upload_to=CRED.models.get_file_path),
        ),
        migrations.AlterField(
            model_name='books',
            name='image',
            field=models.ImageField(default='', upload_to=CRED.models.get_file_path),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='image',
            field=models.ImageField(default='', upload_to=CRED.models.get_file_path),
        ),
        migrations.AlterField(
            model_name='videos',
            name='image',
            field=models.ImageField(default='', upload_to=CRED.models.get_file_path),
        ),
    ]
