# Generated by Django 4.0.3 on 2022-05-17 07:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CRED', '0006_auto_20220516_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='category',
            field=models.CharField(choices=[('Happy', 'Happy'), ('Anger', 'Anger'), ('Fear', 'Fear'), ('Sadness', 'Sadness'), ('Contempt', 'Contempt'), ('Disgust', 'Disgust'), ('Surprise', 'Surprise')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='videos',
            name='image',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.CreateModel(
            name='video_playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRED.videos')),
            ],
        ),
    ]
