# Generated by Django 3.2.10 on 2022-05-17 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRED', '0007_alter_videos_category_alter_videos_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audios',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='books',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='quotes',
            name='date_created',
        ),
    ]
