# Generated by Django 3.2.10 on 2022-05-19 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRED', '0008_auto_20220517_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audios',
            name='category',
            field=models.CharField(choices=[('Happy', 'Happy'), ('anger', 'ager'), ('fear', 'fear'), ('sad', 'sad'), ('contempt', 'contempt'), ('disgust', 'disgust'), ('surprise', 'surprise')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='category',
            field=models.CharField(choices=[('Happy', 'Happy'), ('anger', 'ager'), ('fear', 'fear'), ('sad', 'sad'), ('contempt', 'contempt'), ('disgust', 'disgust'), ('surprise', 'surprise')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='category',
            field=models.CharField(choices=[('Happy', 'Happy'), ('anger', 'ager'), ('fear', 'fear'), ('sad', 'sad'), ('contempt', 'contempt'), ('disgust', 'disgust'), ('surprise', 'surprise')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='videos',
            name='category',
            field=models.CharField(choices=[('Happy', 'Happy'), ('Anger', 'Anger'), ('Fear', 'Fear'), ('Sad', 'Sad'), ('Contempt', 'Contempt'), ('Disgust', 'Disgust'), ('Surprise', 'Surprise')], max_length=200, null=True),
        ),
    ]
