# Generated by Django 3.2.10 on 2022-05-21 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CRED', '0009_auto_20220519_2228'),
    ]

    operations = [
        migrations.CreateModel(
            name='history',
            fields=[
                ('hist_id', models.AutoField(primary_key=True, serialize=False)),
                ('content_id', models.CharField(default='', max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
