# Generated by Django 4.0.3 on 2022-05-22 06:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CRED', '0011_audio_playlist_book_playlist_quote_playlist_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='audio_playlist',
            unique_together={('user', 'audio')},
        ),
        migrations.AlterUniqueTogether(
            name='book_playlist',
            unique_together={('user', 'book')},
        ),
        migrations.AlterUniqueTogether(
            name='quote_playlist',
            unique_together={('user', 'quote')},
        ),
        migrations.AlterUniqueTogether(
            name='video_playlist',
            unique_together={('user', 'video')},
        ),
    ]
